server:
  port:8080
jdbc:
  url: jdbc:mysql://localhost:3306/lab-platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  username: root
  password: 1111
  driverClassName: com.mysql.jdbc.Driver

jwt:
  header: jwtToken
  expiration: 360000
  secret: iwqjhda8232bjgh432[cicada-smile]

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  packagesToScan: com.chp
  # interceptor: com.chp.**.HibernateInterceptor
# 事物配置
spring:
  pointcut: execution(* com.chp..*Service.*(..))
  redis:
    host: 101.200.207.6
    port: 6379
    database: 0
#    password: 123456
