jdbc:
  url: jdbc:mysql://localhost:3380/lab-platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  username: root
  password: 1111
  driverClassName: MySQL

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  packagesToScan: com.chp
  # interceptor: com.chp.**.HibernateInterceptor
# 事物配置
spring:
  pointcut: execution(* com.chp..*Service.*(..))
